Repository Wanted-Pre-Onboarding-Frontend-2/dashboard, pull requests merged in 2022-07, with the labels that each got.

#8 [#5, #6] feat,fix: add dashboard, ad management
  src/components/ad/AdManageContent.tsx
  src/components/ad/AdManageItem.tsx
  src/components/dashboard/DashBoardAd.tsx
  src/components/dashboard/DashBoardMedia.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/pages/Ad/AdManege.tsx
  src/pages/AdManege.tsx
  src/pages/Dashboard.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/dashboard.module.scss
  src/routes/index.tsx
  src/styles/base/_fonts.scss
  src/styles/base/_reset.scss
  src/styles/theme.ts
Labels: feat, fix

#12 fix: change folder, file name
  src/components/campagin/ManageItem.tsx
  src/components/campagin/ManageList.tsx
  src/components/dashboard/OverallReports.tsx
  src/components/dashboard/PlatformReports.tsx
  src/components/layout/Sidebar.tsx
  src/index.tsx
  src/pages/Dashboard.tsx
  src/pages/ManageCampagins.tsx
  src/routes/routes.tsx
Labels: fix

#19 [#7] feat: responsive layout
  src/components/campagin/ManageItem.tsx
  src/components/campagin/ManageList.tsx
  src/components/dashboard/OverallReports.tsx
  src/components/dashboard/PlatformReports.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/pages/Dashboard.tsx
  src/pages/ManageCampagins.tsx
  src/styles/theme.ts
Labels: feat

#25 feat: Create a utility function that sums the data of each channel
  src/types/platform.d.ts
  src/util/getPlatformValues.ts
Labels: feat

#40 docs: update readme
  README.md
  src/api/instance/instance.ts
  src/components/dashboard/OverallDropdowns.tsx
Labels: documentation

#41 fix: modify campaign layout
  src/components/campaign/ManageItem.tsx
Labels: fix
